/* Generated by tools/make_art.py - do not edit. */
#pragma once

#include <stdint.h>

typedef struct {
    uint32_t off;   // into sprites.bin: w*h RGB565 (big-endian), then w*h alpha bytes
    uint16_t w, h;
    int16_t  x, y;  // top-left on screen at the design position
} sprite_t;

enum {
    SPR_BUTTON,
    SPR_TOAST_RESET,
    SPR_AMEN,
    SPR_CARD,
    SPR_RAYS,
    SPR_CUP_LIT,
    SPR_FLAME,
    SPR_ORB,
    SPR_RING,
    SPR_MOTE,
    SPR_COUNT,
};

#define FX       120   // design center of cups, flames, orbs, rings and motes
#define FY       140
#define PILL_X   16
#define PILL_Y   8
#define PILL_W   208
#define PILL_H   46
#define CARD_CX  120
#define CARD_CY  124
#define CARD_W   212
#define CARD_H   136

#define CANDLE_COUNT 24
static const int16_t s_candles[CANDLE_COUNT][2] = {{108, 264}, {132, 264}, {84, 264}, {156, 264}, {60, 264}, {180, 264}, {36, 264}, {204, 264}, {108, 240}, {132, 240}, {84, 240}, {156, 240}, {60, 240}, {180, 240}, {36, 240}, {204, 240}, {108, 216}, {132, 216}, {84, 216}, {156, 216}, {60, 216}, {180, 216}, {36, 216}, {204, 216}};  // cup centers, fill order

static const sprite_t s_sprites[SPR_COUNT] = {
    {      0,  96,  51, 136, 228},  // button
    {  14688, 172,  40,  34, 108},  // toast_reset
    {  35328,  45,  23, 176,  74},  // amen
    {  38433, 215, 141,  13,  55},  // card
    { 129378, 240, 280,   0,   0},  // rays
    { 330978,  16,  17, 112, 131},  // cup_lit
    { 331794,  22,  22, 109, 129},  // flame
    { 333246,  20,  20, 110, 130},  // orb
    { 334446,  36,  36, 102, 122},  // ring
    { 338334,   6,   6, 117, 137},  // mote
};
