"""Generate main/verses.h: the Bible verses (Chinese Union Version, public domain), one of which is shown as
"今日经文" when the prayer scene opens, the UI strings, and two anti-aliased fonts holding just the characters used
(KaiTi for the verse, YaHei for the reference and the UI). Also writes art/verses.txt for proofreading.

Where an excerpt stops before the end of its sentence it ends with "……", so no verse is cut silently.

Fonts: 4-bit coverage (2 px per byte, high nibble first), glyphs cropped to their ink box, looked up by code
point (sorted table, binary search in C).

    python tools/make_text.py
"""
import pathlib

from PIL import Image, ImageDraw, ImageFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "main" / "verses.h"
TXT = ROOT / "art" / "verses.txt"

FONTS = [  # C name, file, px
    ("font_verse", r"C:\Windows\Fonts\STKAITI.TTF", 17),
    ("font_ref", r"C:\Windows\Fonts\msyh.ttc", 13),
]

# (text, reference) - 和合本
VERSES = [
    ("凡劳苦担重担的人可以到我这里来，我就使你们得安息。", "马太福音 11:28"),
    ("耶和华是我的牧者，我必不致缺乏。", "诗篇 23:1"),
    ("你们祈求，就给你们；寻找，就寻见；叩门，就给你们开门。", "马太福音 7:7"),
    ("应当一无挂虑，只要凡事藉着祷告、祈求，和感谢，将你们所要的告诉神。", "腓立比书 4:6"),
    ("我靠着那加给我力量的，凡事都能做。", "腓立比书 4:13"),
    ("神爱世人，甚至将他的独生子赐给他们，叫一切信他的，不致灭亡，反得永生。", "约翰福音 3:16"),
    ("要常常喜乐，不住地祷告，凡事谢恩……", "帖撒罗尼迦前书 5:16-18"),
    ("爱是恒久忍耐，又有恩慈……", "哥林多前书 13:4"),
    ("我留下平安给你们；我将我的平安赐给你们。", "约翰福音 14:27"),
    ("你要专心仰赖耶和华，不可倚靠自己的聪明……", "箴言 3:5"),
    ("愿耶和华赐福给你，保护你。", "民数记 6:24"),
    ("我是世界的光。跟从我的，就不在黑暗里走，必要得着生命的光。", "约翰福音 8:12"),
    ("神是我们的避难所，是我们的力量，是我们在患难中随时的帮助。", "诗篇 46:1"),
    ("凡事都有定期，天下万务都有定时。", "传道书 3:1"),
    ("如今常存的有信，有望，有爱这三样，其中最大的是爱。", "哥林多前书 13:13"),
    ("你们要将一切的忧虑卸给神，因为他顾念你们。", "彼得前书 5:7"),
    ("我就是道路、真理、生命……", "约翰福音 14:6"),
    ("喜乐的心乃是良药……", "箴言 17:22"),
    ("耶和华是我的亮光，是我的拯救，我还怕谁呢？", "诗篇 27:1"),
    ("你们要彼此相爱，像我爱你们一样……", "约翰福音 15:12"),
    ("他必不叫你的脚摇动；保护你的必不打盹。", "诗篇 121:3"),
    ("信就是所望之事的实底，是未见之事的确据。", "希伯来书 11:1"),
    ("你们是世上的光。", "马太福音 5:14"),
    ("清心的人有福了，因为他们必得见神。", "马太福音 5:8"),
    ("使人和睦的人有福了，因为他们必称为神的儿子。", "马太福音 5:9"),
    ("我们晓得万事都互相效力，叫爱神的人得益处……", "罗马书 8:28"),
    ("我的恩典够你用的……", "哥林多后书 12:9"),
    ("这是耶和华所定的日子，我们在其中要高兴欢喜。", "诗篇 118:24"),
    ("你们亲近神，神就必亲近你们。", "雅各书 4:8"),
    ("求主教导我们祷告……", "路加福音 11:1"),
]

UI = {
    "today": "今日经文",
    "hint": "默祷之后，按一下点亮蜡烛",
    "lit_l": "已点亮",
    "lit_r": "支",
}


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_font(path, size, chars):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    pad = size
    glyphs, bits = [], bytearray()
    for ch in chars:
        img = Image.new("L", (size * 3, size * 3), 0)
        ImageDraw.Draw(img).text((pad, pad + ascent), ch, fill=255, font=font, anchor="ls")
        adv = round(font.getlength(ch))
        box = img.getbbox()
        if not box:
            glyphs.append((ord(ch), len(bits), 0, 0, 0, 0, adv))
            continue
        x0, y0, x1, y1 = box
        px = img.load()
        off = len(bits)
        for y in range(y0, y1):
            row = [min(15, (px[x, y] + 8) // 17) for x in range(x0, x1)]
            if len(row) % 2:
                row.append(0)
            bits.extend((row[i] << 4) | row[i + 1] for i in range(0, len(row), 2))
        glyphs.append((ord(ch), off, x1 - x0, y1 - y0, x0 - pad, y0 - pad, adv))
    return ascent, descent, glyphs, bits


def main():
    assert len({v for v, _ in VERSES}) == len(VERSES)
    verse_chars = sorted({c for v, _ in VERSES for c in v})
    ref_chars = sorted({c for _, r in VERSES for c in "—— " + r} | set("".join(UI.values())) | {chr(c) for c in range(32, 127)})

    L = ["/* Generated by tools/make_text.py - do not edit. */", "#pragma once", "", "#include <stdint.h>", "",
         "typedef struct {", "    const char* text;", "    const char* ref;", "} verse_t;", "",
         f"#define VERSE_COUNT {len(VERSES)}", "static const verse_t s_verses[VERSE_COUNT] = {"]
    L += [f"    {{{c_str(v)}, {c_str(r)}}}," for v, r in VERSES]
    L += ["};", ""]
    L += [f"#define TXT_{k.upper():<6} {c_str(v)}" for k, v in UI.items()]
    L += ["", "typedef struct {",
          "    uint32_t off;  // into bits: rows of (w+1)/2 bytes, 4-bit coverage, high nibble first",
          "    uint8_t  w, h;", "    int8_t   x, y;  // ink box offset from the pen x / line top", "    uint8_t  adv;",
          "} cjk_glyph_t;", "", "typedef struct {", "    uint8_t            line_h, ascent;", "    uint16_t           count;",
          "    const uint16_t*    cps;     // sorted code points", "    const cjk_glyph_t* glyphs;", "    const uint8_t*     bits;",
          "} cjk_font_t;", ""]
    for (cname, path, size), cs in zip(FONTS, (verse_chars, ref_chars)):
        ascent, descent, glyphs, bits = build_font(path, size, cs)
        L.append(f"/* {pathlib.Path(path).name} {size} px: {len(glyphs)} glyphs, {len(bits)} bytes */")
        L.append(f"static const uint16_t {cname}_cps[{len(glyphs)}] = {{")
        for i in range(0, len(glyphs), 16):
            L.append("    " + ", ".join(f"0x{g[0]:04X}" for g in glyphs[i:i + 16]) + ",")
        L.append("};")
        L.append(f"static const uint8_t {cname}_bits[] = {{")
        for i in range(0, len(bits), 32):
            L.append("    " + ",".join(f"0x{b:02X}" for b in bits[i:i + 32]) + ",")
        L.append("};")
        L.append(f"static const cjk_glyph_t {cname}_glyphs[{len(glyphs)}] = {{")
        L += [f"    {{{off}, {w}, {h}, {x}, {y}, {adv}}},  // U+{cp:04X}" for cp, off, w, h, x, y, adv in glyphs]
        L.append("};")
        L.append(f"static const cjk_font_t {cname} = {{{ascent + descent + 2}, {ascent}, {len(glyphs)}, {cname}_cps, "
                 f"{cname}_glyphs, {cname}_bits}};")
        L.append("")
        print(f"{cname}: {len(glyphs)} glyphs, {len(bits)} bytes")
    OUT.write_text("\n".join(L), encoding="utf-8", newline="\n")
    TXT.write_text("祷告时光：进入祷告场景时，随机显示一则圣经经文摘句（和合本）作为「今日经文」\n"
                   "摘句未到句末的，以「……」结尾。请对照和合本核对字句。\n\n"
                   + "\n".join(f"{i + 1:2d}. {v}\n    ——{r}" for i, (v, r) in enumerate(VERSES)) + "\n", encoding="utf-8-sig")


if __name__ == "__main__":
    main()
