"""Generate main/font_ui_data.h: anti-aliased proportional UI fonts (the merit counter uses the bold ones).

Printable ASCII (32..126) rendered from Segoe UI (ships with Windows) at a few pixel sizes,
stored as 4-bit coverage (2 pixels per byte, high nibble first), cropped to each glyph's ink box.

    python tools/make_ui_font.py
"""
import os

from PIL import Image, ImageDraw, ImageFont

FONTS = [  # C name, file, pixel size
    ("ui_font_s", r"C:\Windows\Fonts\segoeui.ttf", 13),
    ("ui_font_m", r"C:\Windows\Fonts\segoeui.ttf", 20),
    ("ui_font_l", r"C:\Windows\Fonts\segoeuisl.ttf", 30),
    ("ui_font_lb", r"C:\Windows\Fonts\segoeuib.ttf", 30),
    ("ui_font_xl", r"C:\Windows\Fonts\segoeuib.ttf", 40),
]
OUT = os.path.join(os.path.dirname(__file__), "..", "main", "font_ui_data.h")


def build(path, size):
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    pad = size
    glyphs, bits = [], []
    for code in range(32, 127):
        ch = chr(code)
        img = Image.new("L", (size * 3, size * 3), 0)
        ImageDraw.Draw(img).text((pad, pad + ascent), ch, fill=255, font=font, anchor="ls")
        adv = round(font.getlength(ch))
        box = img.getbbox()
        if not box:
            glyphs.append((len(bits), 0, 0, 0, 0, adv))
            continue
        x0, y0, x1, y1 = box
        w, h = x1 - x0, y1 - y0
        px = img.load()
        off = len(bits)
        for y in range(y0, y1):
            row = [min(15, (px[x, y] + 8) // 17) for x in range(x0, x1)]
            if len(row) % 2:
                row.append(0)
            bits.extend((row[i] << 4) | row[i + 1] for i in range(0, len(row), 2))
        glyphs.append((off, w, h, x0 - pad, y0 - pad, adv))
    cap = glyphs[ord("H") - 32][4]  # top of the capitals, from the line top
    return ascent, descent, cap, glyphs, bits


def main():
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* Generated by tools/make_ui_font.py - do not edit. */\n#pragma once\n\n#include \"ui.h\"\n")
        for name, path, size in FONTS:
            ascent, descent, cap, glyphs, bits = build(path, size)
            f.write(f"\n/* {os.path.basename(path)} {size} px: {len(bits)} bytes of 4-bit coverage */\n")
            f.write(f"static const uint8_t {name}_bits[] = {{\n")
            for i in range(0, len(bits), 24):
                f.write("    " + ",".join(f"0x{b:02X}" for b in bits[i:i + 24]) + ",\n")
            f.write("};\n")
            f.write(f"static const ui_glyph_t {name}_glyphs[95] = {{\n")
            for code, (off, w, h, x, y, adv) in zip(range(32, 127), glyphs):
                f.write(f"    {{{off}, {w}, {h}, {x}, {y}, {adv}}}, /* {chr(code) if chr(code) != chr(92) else 'backslash'} */\n")
            f.write("};\n")
            f.write(f"const ui_font_t {name} = {{{ascent + descent}, {ascent}, {cap}, {name}_glyphs, {name}_bits}};\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
